### ISSUE TITLE
onWorkerStart后，是不是要先 $kernel->boot(); ？

### ISSUE THREAD

**Issue by tourze** [manyou-io/php#1]
https://github.com/manyou-io/php/blob/bdccbddac105f4057d4ac8c1e22ef95f1f05d94d/src/WorkermanSymfonyRuntime/Runner.php#L64

从 Symfony 的启动流程来看，这里 boot 的话应该能减少请求中的处理时间。

另外，理论上为了减少内存泄露，是不是应该每次处理请求前，主动 $this->container->get('services_resetter')->reset(); ？

**Comment by bohanwood** [comment]
嗯，可以研究一下。

现在应该是 handle 的时候会 boot，应该是只会 boot 一次？也就是第一次请求会慢一些。

reset 的话，现在应该是有的。前段时间项目里出了个泄露，implement Reset Interface 之后好了。可能是 Symfony kernel 会自动 reset？

**Comment by bohanwood** [comment]
看来这些工作 Symfony Kernel 已经帮我们做了，并不需要操心

handle 里面如果没有 boot 会 boot:

https://github.com/symfony/symfony/blob/c79d4ab7e787eb27d83581ccb8e15a4e11e88df3/src/Symfony/Component/HttpKernel/Kernel.php#L169-L179

boot 如果已经 boot 会 reset 并直接 return:

https://github.com/symfony/symfony/blob/c79d4ab7e787eb27d83581ccb8e15a4e11e88df3/src/Symfony/Component/HttpKernel/Kernel.php#L107-L119

**Comment by tourze** [comment]
> 看来这些工作 Symfony Kernel 已经帮我们做了，并不需要操心
> 
> handle 里面如果没有 boot 会 boot:
> 
> https://github.com/symfony/symfony/blob/c79d4ab7e787eb27d83581ccb8e15a4e11e88df3/src/Symfony/Component/HttpKernel/Kernel.php#L169-L179
> 
> boot 如果已经 boot 会 reset 并直接 return:
> 
> https://github.com/symfony/symfony/blob/c79d4ab7e787eb27d83581ccb8e15a4e11e88df3/src/Symfony/Component/HttpKernel/Kernel.php#L107-L119

如果按照已有的代码来看，boot 在整个worker的声明周期中只会执行一次，services_resetter 的行为就跟 fpm 不太一致了。。开发者需要主动监听 terminate 事件来主动 reset 吗？

**Comment by bohanwood** [comment]
你可能理解错了？这里明明是 handle 一次执行一次的呀。只要 tag 了 Reset Interface 就会在这里被 reset 呀

**Comment by bohanwood** [comment]
那个是在 onMessage 里面被调用的，也就是请求来的时候。onWorkStart 只是创建handler

**Comment by tourze** [comment]
我回头学习下symfony的执行流程

**Comment by bohanwood** [comment]
决定之后改一下，在 onWorkerStart 里面 boot 了。
因为 boot 之后可以从 container 里面拿服务，实现依赖注入及功能拓展。

https://github.com/manyou-io/php/blob/bdccbddac105f4057d4ac8c1e22ef95f1f05d94d/src/WorkermanSymfonyRuntime/Runner.php#L63-L72

比如这里 blackfire 的 logger，要是直接从服务容器拿就方便多了。
OnMessageAdapter 也可以直接在容器中替换服务。
